[package]
name = "climb-db"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
diesel = { version = "2.2.2", features = ["postgres", "chrono"] }
diesel_migrations = { version = "2.2.0", features = ["postgres"] }
postgis_diesel = "2.4.1"
