name: ci

on:
  pull_request:
  push:
    branches:
    - main
  schedule:
  - cron: '00 01 * * *'

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        toolchain:
        - stable
        - beta
        - nightly
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Install PostgreSQL on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install postgresql@16
        brew link postgresql@16
    - name: Install PostgreSQL on Windows
      if: matrix.os == 'windows-latest'
      run: choco install postgresql
    - name: Run unit tests
      run: cargo test --all-features --lib --bins
  integration-test:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
        - stable
        - beta
        - nightly
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Run integration tests
      run: cargo test --test '*'
      env:
        TEST_DATABASE_URL: postgres://postgres@localhost
